import React from 'react'
import Head from 'next/head'
import {AddForm} from '../components/index.js';


export default function newInvest() {

  const dataForm = {
    title: 'New Investment'
  }

  return (
    <div>
      <Head>
        <title>Create Invest</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AddForm/>
    </div>
  );
}
